---
title: "Timeline of COVID-19 in Canada: Technical report"
format: gfm
---

## Metrics in this dataset

The following table describes 1) the short and long names of the metrics in this dataset, 2) for each metric, the definition of "value" and "daily value", and 3) the source of the values for each geographic level (health region-level, HR; province/territory-level, PT; Canada-level, CAN). For example, for cases, the the PT-level and and CAN-level values are aggregated from the HR-level values, whereas CAN-level vaccine coverage data are not aggregated from PT-level values, but is actually an independent dataset. For case and death data, there a few exceptions where the PT-level values are not aggregated from the HR-level values these are listed below the table.

```{r, echo=FALSE}
# read values.json
values <- jsonlite::read_json("../values/values.json")
# function: format geo
format_geo <- function(x) {
  dplyr::case_when(
    x == "na" ~ "N/A",
    x == "hr" ~ "HR",
    x == "pt" ~ "PT",
    x == "can" ~ "CAN"
  )
}
# format data
tab_metric <- lapply(seq_along(values), function(x) {
  v <- values[[x]]
  data.frame(
    `Metric` = paste0("`", v$name, "` (", v$name_long, ")"),
    `Description` = paste0("**Value**: ", v$value, "<br>**Daily value**: ", v$value_daily),
    `HR` = format_geo(v$geo$hr),
    `PT` = format_geo(v$geo$pt),
    `CAN` = format_geo(v$geo$can)
  )
}) |> dplyr::bind_rows()
# format table
knitr::kable(tab_metric)
```

As mentioned above, some PT-level case and death data are not aggregated from the HR-level values after a certain date. This is because the available PT-level data is of significantly higher accuracy or temporal resolution and better reflects the true number of cases and deaths if sub-provincial geographic resolution is not required. The following list includes all such substitutions:

Case data:

- NB: 2022-12-17 onward
- SK: 2022-02-12 onward

Death data:

- AB: 2020-03-06 onward
- ON: 2020-03-01 onward
- SK: 2022-02-12 onward

For more details, see this [GitHub issue](https://github.com/ccodwg/CovidTimelineCanada/issues/120).
